### PR TITLE
Adds step 10 to support power up pills

### PR DESCRIPTION
**Pull request by mzampetakis**
This PR aims to add support to power-up pills. 
Multiple power-up pills are supported.
It makes use of go timers and Mutexes.

### CODE REVIEW

**Comment by danicat** [comment]
First of all, thanks a lot for your contribution. I was holding back reviewing this because you originally submitted as a draft, but it seems now you have finished the work.

I've noticed you implemented it based on an older version of the code. I've made some fixes in preparation for my talk at Cloud Next UK (like not using public types when they aren't needed) which will need to be applied to your code.

Are you still willing to work on this?

**Comment by mzampetakis** [comment]
Sure, I started developing it a few months ago so the latest changes are not included.

I suppose that I have to get the code from step09 and  manually "rebase" the newly added code from this commit using this step. Is that correct?

**Comment by danicat** [comment]
Yes, unfortunately there is no easy way of doing that the way the code is currently organised.

**Comment by mzampetakis** [comment]
So, I have rebased my branch and rewrote the step's 10 code using the latest changes. However, now it's not so easy to check the changes as 'Changed Files' is not so convenient. If you are not able to review this PR, please feel free to close it and I will create a new one using the updated steps!

**Pull request merged**
